name: CD

on:
    pull_request:
        branches: [main]

jobs:
    lint-commits:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetch all history for commit linting

            - name: Lint commits # Lint commit messages
              uses: wagoid/commitlint-github-action@v6

    release:
        runs-on: ubuntu-latest # Use the latest Ubuntu runner
        needs: lint-commits # Wait for commit linting to pass

        permissions:
            contents: write # Allow semantic-release to push new tags
            issues: write # Allow semantic-release to create GitHub releases
            pull-requests: write # Allow semantic-release to update pull requests

        steps:
            - uses: actions/checkout@v4 # Check out the repository
            - uses: actions/setup-node@v4 # Set up Node.js
              with:
                  node-version: 20

            - run: npm ci # Install dependencies

            - run: npx semantic-release # Run semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
